export const INVITE = 'https://discord.com/oauth2/authorize?client_id=1489362526880796903';
export const SUPPORT = 'https://discord.gg/Y67yNmsPuf';
export const WEBSITE = 'https://pocket-tool.xyz/';

export enum Emoji {
  Boost = '<:boost:1533281851475628193>',
  Correct = '<:correct:1533281900528013333>',
  Wrong = '<:wrong:1533281955984965812>',
  Exclamation = '<:exclamation:1533281999912046753>',
  Newbie = '<:newbie:1533282058640687294>',
  Owner = '<:owner:1533282111170150430>',
  Spark = '<:spark:1533282156040687696>',
  Wumpus = '<:wumpus:1533282200613556227>',
  Ping = '<:at:1533282869861023885>',
  Calendar = '<:calendar:1533283045367349409>',
  Clock = '<:clock:1533283098345607188>',
  Discord = '<:discord:1535332684132519956>',
  Home = '<:home:1533283376176566322>',
  GIF = '<:gif:1533283453989158982>',
  Link = '<:link:1533283554845266000>',
  People = '<:people:1533283678191484948>',
  Role = '<:role:1533283748903129098>',
  Translate = '<:translate:1533284546097840228>',
  Quote = '<:quote:1533288342052016138>',
  Search = '<:search:1535622633058598942>',
  // pagination
  Previous = '<:previous:1535622582454194228>',
  Next = '<:next:1535622608429654037>',
  // twitter
  Bookmark = '<:twitter_bookmark:1504947779548479669>',
  Like = '<:twitter_like:1504947769717162076>',
  Repost = '<:twitter_repost:1504947753745121421>',
  Reply = '<:twitter_reply:1504947725471322286>',
  Verified = '<:twitter_verified:1504947691363238008>',
}

export const MESSAGE_BLOCK_REASONS = {
  20016: {
    reason: "the channel's slowmode settings",
    article: 'https://support.discord.com/hc/en-us/articles/360016150952',
  },
  200000: {
    reason: "the server's AutoMod setup",
    article: 'https://support.discord.com/hc/en-us/articles/4421269296535',
  },
  50013: {
    reason: "the channel's permission setup",
    article: 'https://support.discord.com/hc/en-us/articles/10543994968087',
  },
};

export const AZURE_LANGUAGES = [
  { name: 'Afrikaans', code: 'af', flag: '🇿🇦' },
  { name: 'Amharic', code: 'am', flag: '🇪🇹' },
  { name: 'Arabic', code: 'ar', flag: '🇸🇦' },
  { name: 'Assamese', code: 'as', flag: '🇮🇳' },
  { name: 'Azerbaijani', code: 'az', flag: '🇦🇿' },
  { name: 'Bashkir', code: 'ba', flag: '🇷🇺' },
  { name: 'Belarusian', code: 'be', flag: '🇧🇾' },
  { name: 'Bulgarian', code: 'bg', flag: '🇧🇬' },
  { name: 'Bhojpuri', code: 'bho', flag: '🇮🇳' },
  { name: 'Bengali', code: 'bn', flag: '🇧🇩' },
  { name: 'Tibetan', code: 'bo', flag: '🇨🇳' },
  { name: 'Bodo', code: 'brx', flag: '🇮🇳' },
  { name: 'Bosnian', code: 'bs', flag: '🇧🇦' },
  { name: 'Catalan', code: 'ca', flag: '🇪🇸' },
  { name: 'Czech', code: 'cs', flag: '🇨🇿' },
  { name: 'Welsh', code: 'cy', flag: '🇬🇧' },
  { name: 'Danish', code: 'da', flag: '🇩🇰' },
  { name: 'German', code: 'de', flag: '🇩🇪' },
  { name: 'Dogri', code: 'doi', flag: '🇮🇳' },
  { name: 'Lower Sorbian', code: 'dsb', flag: '🇩🇪' },
  { name: 'Divehi', code: 'dv', flag: '🇲🇻' },
  { name: 'Greek', code: 'el', flag: '🇬🇷' },
  { name: 'English', code: 'en', flag: '🇺🇸' },
  { name: 'Spanish', code: 'es', flag: '🇪🇸' },
  { name: 'Spanish (Mexico)', code: 'es-MX', flag: '🇲🇽' },
  { name: 'Estonian', code: 'et', flag: '🇪🇪' },
  { name: 'Basque', code: 'eu', flag: '🇪🇸' },
  { name: 'Persian', code: 'fa', flag: '🇮🇷' },
  { name: 'Finnish', code: 'fi', flag: '🇫🇮' },
  { name: 'Filipino', code: 'fil', flag: '🇵🇭' },
  { name: 'Fijian', code: 'fj', flag: '🇫🇯' },
  { name: 'Faroese', code: 'fo', flag: '🇫🇴' },
  { name: 'French', code: 'fr', flag: '🇫🇷' },
  { name: 'French (Canada)', code: 'fr-CA', flag: '🇨🇦' },
  { name: 'Irish', code: 'ga', flag: '🇮🇪' },
  { name: 'Galician', code: 'gl', flag: '🇪🇸' },
  { name: 'Konkani', code: 'gom', flag: '🇮🇳' },
  { name: 'Gujarati', code: 'gu', flag: '🇮🇳' },
  { name: 'Hausa', code: 'ha', flag: '🇳🇬' },
  { name: 'Hebrew', code: 'he', flag: '🇮🇱' },
  { name: 'Hindi', code: 'hi', flag: '🇮🇳' },
  { name: 'Chhattisgarhi', code: 'hne', flag: '🇮🇳' },
  { name: 'Croatian', code: 'hr', flag: '🇭🇷' },
  { name: 'Upper Sorbian', code: 'hsb', flag: '🇩🇪' },
  { name: 'Haitian Creole', code: 'ht', flag: '🇭🇹' },
  { name: 'Hungarian', code: 'hu', flag: '🇭🇺' },
  { name: 'Armenian', code: 'hy', flag: '🇦🇲' },
  { name: 'Indonesian', code: 'id', flag: '🇮🇩' },
  { name: 'Igbo', code: 'ig', flag: '🇳🇬' },
  { name: 'Inuinnaqtun', code: 'ikt', flag: '🇨🇦' },
  { name: 'Icelandic', code: 'is', flag: '🇮🇸' },
  { name: 'Italian', code: 'it', flag: '🇮🇹' },
  { name: 'Inuktitut', code: 'iu', flag: '🇨🇦' },
  { name: 'Inuktitut (Latin)', code: 'iu-Latn', flag: '🇨🇦' },
  { name: 'Japanese', code: 'ja', flag: '🇯🇵' },
  { name: 'Georgian', code: 'ka', flag: '🇬🇪' },
  { name: 'Kazakh', code: 'kk', flag: '🇰🇿' },
  { name: 'Khmer', code: 'km', flag: '🇰🇭' },
  { name: 'Northern Kurdish', code: 'kmr', flag: '🇹🇷' },
  { name: 'Kannada', code: 'kn', flag: '🇮🇳' },
  { name: 'Korean', code: 'ko', flag: '🇰🇷' },
  { name: 'Kashmiri', code: 'ks', flag: '🇮🇳' },
  { name: 'Central Kurdish', code: 'ku', flag: '🇮🇶' },
  { name: 'Kyrgyz', code: 'ky', flag: '🇰🇬' },
  { name: 'Luxembourgish', code: 'lb', flag: '🇱🇺' },
  { name: 'Lingala', code: 'ln', flag: '🇨🇩' },
  { name: 'Lao', code: 'lo', flag: '🇱🇦' },
  { name: 'Lithuanian', code: 'lt', flag: '🇱🇹' },
  { name: 'Ganda', code: 'lug', flag: '🇺🇬' },
  { name: 'Latvian', code: 'lv', flag: '🇱🇻' },
  { name: 'Literary Chinese', code: 'lzh', flag: '🇨🇳' },
  { name: 'Maithili', code: 'mai', flag: '🇮🇳' },
  { name: 'Malagasy', code: 'mg', flag: '🇲🇬' },
  { name: 'Maori', code: 'mi', flag: '🇳🇿' },
  { name: 'Macedonian', code: 'mk', flag: '🇲🇰' },
  { name: 'Malayalam', code: 'ml', flag: '🇮🇳' },
  { name: 'Mongolian (Cyrillic)', code: 'mn-Cyrl', flag: '🇲🇳' },
  { name: 'Mongolian (Traditional)', code: 'mn-Mong', flag: '🇲🇳' },
  { name: 'Manipuri', code: 'mni', flag: '🇮🇳' },
  { name: 'Marathi', code: 'mr', flag: '🇮🇳' },
  { name: 'Malay', code: 'ms', flag: '🇲🇾' },
  { name: 'Maltese', code: 'mt', flag: '🇲🇹' },
  { name: 'Hmong', code: 'mww', flag: '🇨🇳' },
  { name: 'Burmese', code: 'my', flag: '🇲🇲' },
  { name: 'Norwegian Bokmål', code: 'nb', flag: '🇳🇴' },
  { name: 'Nepali', code: 'ne', flag: '🇳🇵' },
  { name: 'Dutch', code: 'nl', flag: '🇳🇱' },
  { name: 'Northern Sotho', code: 'nso', flag: '🇿🇦' },
  { name: 'Nyanja', code: 'nya', flag: '🇲🇼' },
  { name: 'Odia', code: 'or', flag: '🇮🇳' },
  { name: 'Querétaro Otomi', code: 'otq', flag: '🇲🇽' },
  { name: 'Punjabi', code: 'pa', flag: '🇮🇳' },
  { name: 'Polish', code: 'pl', flag: '🇵🇱' },
  { name: 'Dari', code: 'prs', flag: '🇦🇫' },
  { name: 'Pashto', code: 'ps', flag: '🇦🇫' },
  { name: 'Portuguese (Brazil)', code: 'pt', flag: '🇧🇷' },
  { name: 'Portuguese (Portugal)', code: 'pt-PT', flag: '🇵🇹' },
  { name: 'Romanian', code: 'ro', flag: '🇷🇴' },
  { name: 'Russian', code: 'ru', flag: '🇷🇺' },
  { name: 'Rundi', code: 'run', flag: '🇧🇮' },
  { name: 'Kinyarwanda', code: 'rw', flag: '🇷🇼' },
  { name: 'Sindhi', code: 'sd', flag: '🇵🇰' },
  { name: 'Sinhala', code: 'si', flag: '🇱🇰' },
  { name: 'Slovak', code: 'sk', flag: '🇸🇰' },
  { name: 'Slovenian', code: 'sl', flag: '🇸🇮' },
  { name: 'Samoan', code: 'sm', flag: '🇼🇸' },
  { name: 'Shona', code: 'sn', flag: '🇿🇼' },
  { name: 'Somali', code: 'so', flag: '🇸🇴' },
  { name: 'Albanian', code: 'sq', flag: '🇦🇱' },
  { name: 'Serbian (Cyrillic)', code: 'sr-Cyrl', flag: '🇷🇸' },
  { name: 'Serbian (Latin)', code: 'sr-Latn', flag: '🇷🇸' },
  { name: 'Sesotho', code: 'st', flag: '🇱🇸' },
  { name: 'Swedish', code: 'sv', flag: '🇸🇪' },
  { name: 'Swahili', code: 'sw', flag: '🇰🇪' },
  { name: 'Tamil', code: 'ta', flag: '🇮🇳' },
  { name: 'Telugu', code: 'te', flag: '🇮🇳' },
  { name: 'Thai', code: 'th', flag: '🇹🇭' },
  { name: 'Tigrinya', code: 'ti', flag: '🇪🇷' },
  { name: 'Turkmen', code: 'tk', flag: '🇹🇲' },
  // { name: 'Klingon (Latin)', code: 'tlh-Latn', flag: '🖖' },
  // { name: 'Klingon (pIqaD)', code: 'tlh-Piqd', flag: '🖖' },
  { name: 'Tswana', code: 'tn', flag: '🇧🇼' },
  { name: 'Tongan', code: 'to', flag: '🇹🇴' },
  { name: 'Turkish', code: 'tr', flag: '🇹🇷' },
  { name: 'Tatar', code: 'tt', flag: '🇷🇺' },
  { name: 'Tahitian', code: 'ty', flag: '🇵🇫' },
  { name: 'Uyghur', code: 'ug', flag: '🇨🇳' },
  { name: 'Ukrainian', code: 'uk', flag: '🇺🇦' },
  { name: 'Urdu', code: 'ur', flag: '🇵🇰' },
  { name: 'Uzbek', code: 'uz', flag: '🇺🇿' },
  { name: 'Vietnamese', code: 'vi', flag: '🇻🇳' },
  { name: 'Xhosa', code: 'xh', flag: '🇿🇦' },
  { name: 'Yoruba', code: 'yo', flag: '🇳🇬' },
  { name: 'Yucatec Maya', code: 'yua', flag: '🇲🇽' },
  { name: 'Cantonese (Traditional)', code: 'yue', flag: '🇭🇰' },
  { name: 'Chinese (Simplified)', code: 'zh-Hans', flag: '🇨🇳' },
  { name: 'Chinese (Traditional)', code: 'zh-Hant', flag: '🇹🇼' },
  { name: 'Zulu', code: 'zu', flag: '🇿🇦' },
] as const;

export const ELEVEN_LABS_LANGUAGES = [
  { name: 'Arabic', code: 'ar' },
  { name: 'Bulgarian', code: 'bg' },
  { name: 'Chinese', code: 'zh' },
  { name: 'Croatian', code: 'hr' },
  { name: 'Czech', code: 'cs' },
  { name: 'Danish', code: 'da' },
  { name: 'Dutch', code: 'nl' },
  { name: 'English', code: 'en' },
  { name: 'Filipino', code: 'fil' },
  { name: 'Finnish', code: 'fi' },
  { name: 'French', code: 'fr' },
  { name: 'German', code: 'de' },
  { name: 'Greek', code: 'el' },
  { name: 'Hungarian', code: 'hu' },
  { name: 'Hindi', code: 'hi' },
  { name: 'Indonesian', code: 'id' },
  { name: 'Italian', code: 'it' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Korean', code: 'ko' },
  { name: 'Malay', code: 'ms' },
  { name: 'Norwegian', code: 'no' },
  { name: 'Polish', code: 'pl' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Romanian', code: 'ro' },
  { name: 'Russian', code: 'ru' },
  { name: 'Slovak', code: 'sk' },
  { name: 'Spanish', code: 'es' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Tamil', code: 'ta' },
  { name: 'Turkish', code: 'tr' },
  { name: 'Ukrainian', code: 'uk' },
  { name: 'Vietnamese', code: 'vi' },
] as const;
