export const CONNECTION_SERVICES = [
  // { name: 'Amazon Music', service: 'amazon-music', emoji: '' },
  { name: 'Battle.net', service: 'battlenet', emoji: 'BattleNet' },
  // { name: 'Bluesky', service: 'bluesky', emoji: '' },
  // { name: 'Bungie', service: 'bungie', emoji: '' },
  { name: 'Crunchyroll', service: 'crunchyroll', emoji: 'Crunchyroll' },
  // { name: 'Domain', service: 'domain', emoji: '' },
  { name: 'eBay', service: 'ebay', emoji: 'eBay' },
  { name: 'Epic Games', service: 'epicgames', emoji: 'EpicGames' },
  { name: 'Facebook', service: 'facebook', emoji: 'Facebook' },
  { name: 'GitHub', service: 'github', emoji: 'GitHub' },
  { name: 'PayPal', service: 'paypal', emoji: 'PayPal' },
  { name: 'PlayStation Network', service: 'playstationnetwork', emoji: 'PlayStation' },
  { name: 'Reddit', service: 'reddit', emoji: 'Reddit' },
  { name: 'Riot Games', service: 'riotgames', emoji: 'RiotGames' },
  // { name: 'Roblox', service: 'roblox', emoji: '' },
  { name: 'Spotify', service: 'spotify', emoji: 'Spotify' },
  { name: 'Steam', service: 'steam', emoji: 'Steam' },
  { name: 'Twitch', service: 'twitch', emoji: 'Twitch' },
  { name: 'X (Twitter)', service: 'twitter', emoji: 'Twitter' },
  { name: 'Xbox', service: 'xbox', emoji: 'Xbox' },
  { name: 'YouTube', service: 'youtube', emoji: 'YouTube' },
] as const;
