export const SUPPORTED_LANGUAGES = [
  { name: 'Abkhaz', code: 'ab', flag: '' },
  { name: 'Afar', code: 'aa', flag: '' },
  { name: 'Afrikaans', code: 'af', flag: '🇿🇦' },
  { name: 'Akan', code: 'ak', flag: '🇬🇭' },
  { name: 'Albanian', code: 'sq', flag: '🇦🇱' },
  { name: 'Amharic', code: 'am', flag: '🇪🇹' },
  { name: 'Arabic', code: 'ar', flag: '🇸🇦' },
  { name: 'Aragonese', code: 'an', flag: '🇪🇸' },
  { name: 'Armenian', code: 'hy', flag: '🇦🇲' },
  { name: 'Assamese', code: 'as', flag: '🇮🇳' },
  { name: 'Avaric', code: 'av', flag: '🇷🇺' },
  { name: 'Avestan', code: 'ae', flag: '' },
  { name: 'Aymara', code: 'ay', flag: '🇧🇴' },
  { name: 'Azerbaijani', code: 'az', flag: '🇦🇿' },
  { name: 'Bambara', code: 'bm', flag: '🇲🇱' },
  { name: 'Bashkir', code: 'ba', flag: '🇷🇺' },
  { name: 'Basque', code: 'eu', flag: '🇪🇸' },
  { name: 'Belarusian', code: 'be', flag: '🇧🇾' },
  { name: 'Bengali', code: 'bn', flag: '🇧🇩' },
  { name: 'Bihari', code: 'bh', flag: '🇮🇳' },
  { name: 'Bislama', code: 'bi', flag: '🇻🇺' },
  { name: 'Bosnian', code: 'bs', flag: '🇧🇦' },
  { name: 'Breton', code: 'br', flag: '🇫🇷' },
  { name: 'Bulgarian', code: 'bg', flag: '🇧🇬' },
  { name: 'Burmese', code: 'my', flag: '🇲🇲' },
  { name: 'Catalan; Valencian', code: 'ca', flag: '🇪🇸' },
  { name: 'Chamorro', code: 'ch', flag: '🇬🇺' },
  { name: 'Chechen', code: 'ce', flag: '🇷🇺' },
  { name: 'Chichewa; Chewa; Nyanja', code: 'ny', flag: '🇲🇼' },
  { name: 'Chinese', code: 'zh', flag: '🇨🇳' },
  { name: 'Chuvash', code: 'cv', flag: '🇷🇺' },
  { name: 'Cornish', code: 'kw', flag: '🇬🇧' },
  { name: 'Corsican', code: 'co', flag: '🇫🇷' },
  { name: 'Cree', code: 'cr', flag: '🇨🇦' },
  { name: 'Croatian', code: 'hr', flag: '🇭🇷' },
  { name: 'Czech', code: 'cs', flag: '🇨🇿' },
  { name: 'Danish', code: 'da', flag: '🇩🇰' },
  { name: 'Divehi; Dhivehi; Maldivian', code: 'dv', flag: '🇲🇻' },
  { name: 'Dutch', code: 'nl', flag: '🇳🇱' },
  { name: 'English', code: 'en', flag: '🇬🇧' },
  { name: 'Esperanto', code: 'eo', flag: '' },
  { name: 'Estonian', code: 'et', flag: '🇪🇪' },
  { name: 'Ewe', code: 'ee', flag: '🇬🇭' },
  { name: 'Faroese', code: 'fo', flag: '🇫🇴' },
  { name: 'Fijian', code: 'fj', flag: '🇫🇯' },
  { name: 'Finnish', code: 'fi', flag: '🇫🇮' },
  { name: 'French', code: 'fr', flag: '🇫🇷' },
  { name: 'Fula; Fulah; Pulaar; Pular', code: 'ff', flag: '🇸🇳' },
  { name: 'Galician', code: 'gl', flag: '🇪🇸' },
  { name: 'Georgian', code: 'ka', flag: '🇬🇪' },
  { name: 'German', code: 'de', flag: '🇩🇪' },
  { name: 'Greek, Modern', code: 'el', flag: '🇬🇷' },
  { name: 'Guaraní', code: 'gn', flag: '🇵🇾' },
  { name: 'Gujarati', code: 'gu', flag: '🇮🇳' },
  { name: 'Haitian; Haitian Creole', code: 'ht', flag: '🇭🇹' },
  { name: 'Hausa', code: 'ha', flag: '🇳🇬' },
  { name: 'Hebrew (modern)', code: 'he', flag: '🇮🇱' },
  { name: 'Herero', code: 'hz', flag: '🇳🇦' },
  { name: 'Hindi', code: 'hi', flag: '🇮🇳' },
  { name: 'Hiri Motu', code: 'ho', flag: '🇵🇬' },
  { name: 'Hungarian', code: 'hu', flag: '🇭🇺' },
  { name: 'Interlingua', code: 'ia', flag: '' },
  { name: 'Indonesian', code: 'id', flag: '🇮🇩' },
  { name: 'Interlingue', code: 'ie', flag: '' },
  { name: 'Irish', code: 'ga', flag: '🇮🇪' },
  { name: 'Igbo', code: 'ig', flag: '🇳🇬' },
  { name: 'Inupiaq', code: 'ik', flag: '🇺🇸' },
  { name: 'Ido', code: 'io', flag: '' },
  { name: 'Icelandic', code: 'is', flag: '🇮🇸' },
  { name: 'Italian', code: 'it', flag: '🇮🇹' },
  { name: 'Inuktitut', code: 'iu', flag: '🇨🇦' },
  { name: 'Japanese', code: 'ja', flag: '🇯🇵' },
  { name: 'Javanese', code: 'jv', flag: '🇮🇩' },
  { name: 'Kalaallisut, Greenlandic', code: 'kl', flag: '🇬🇱' },
  { name: 'Kannada', code: 'kn', flag: '🇮🇳' },
  { name: 'Kanuri', code: 'kr', flag: '🇳🇬' },
  { name: 'Kashmiri', code: 'ks', flag: '🇮🇳' },
  { name: 'Kazakh', code: 'kk', flag: '🇰🇿' },
  { name: 'Khmer', code: 'km', flag: '🇰🇭' },
  { name: 'Kikuyu, Gikuyu', code: 'ki', flag: '🇰🇪' },
  { name: 'Kinyarwanda', code: 'rw', flag: '🇷🇼' },
  { name: 'Kirghiz, Kyrgyz', code: 'ky', flag: '🇰🇬' },
  { name: 'Komi', code: 'kv', flag: '🇷🇺' },
  { name: 'Kongo', code: 'kg', flag: '🇨🇩' },
  { name: 'Korean', code: 'ko', flag: '🇰🇷' },
  { name: 'Kurdish', code: 'ku', flag: '🇹🇷' },
  { name: 'Kwanyama, Kuanyama', code: 'kj', flag: '🇳🇦' },
  { name: 'Latin', code: 'la', flag: '🇻🇦' },
  { name: 'Luxembourgish, Letzeburgesch', code: 'lb', flag: '🇱🇺' },
  { name: 'Luganda', code: 'lg', flag: '🇺🇬' },
  { name: 'Limburgish, Limburgan, Limburger', code: 'li', flag: '🇳🇱' },
  { name: 'Lingala', code: 'ln', flag: '🇨🇩' },
  { name: 'Lao', code: 'lo', flag: '🇱🇦' },
  { name: 'Lithuanian', code: 'lt', flag: '🇱🇹' },
  { name: 'Luba-Katanga', code: 'lu', flag: '🇨🇩' },
  { name: 'Latvian', code: 'lv', flag: '🇱🇻' },
  { name: 'Manx', code: 'gv', flag: '🇮🇲' },
  { name: 'Macedonian', code: 'mk', flag: '🇲🇰' },
  { name: 'Malagasy', code: 'mg', flag: '🇲🇬' },
  { name: 'Malay', code: 'ms', flag: '🇲🇾' },
  { name: 'Malayalam', code: 'ml', flag: '🇮🇳' },
  { name: 'Maltese', code: 'mt', flag: '🇲🇹' },
  { name: 'Māori', code: 'mi', flag: '🇳🇿' },
  { name: 'Marathi (Marāṭhī)', code: 'mr', flag: '🇮🇳' },
  { name: 'Marshallese', code: 'mh', flag: '🇲🇭' },
  { name: 'Mongolian', code: 'mn', flag: '🇲🇳' },
  { name: 'Nauru', code: 'na', flag: '🇳🇷' },
  { name: 'Navajo, Navaho', code: 'nv', flag: '🇺🇸' },
  { name: 'Norwegian Bokmål', code: 'nb', flag: '🇳🇴' },
  { name: 'North Ndebele', code: 'nd', flag: '🇿🇼' },
  { name: 'Nepali', code: 'ne', flag: '🇳🇵' },
  { name: 'Ndonga', code: 'ng', flag: '🇳🇦' },
  { name: 'Norwegian Nynorsk', code: 'nn', flag: '🇳🇴' },
  { name: 'Norwegian', code: 'no', flag: '🇳🇴' },
  { name: 'Nuosu', code: 'ii', flag: '🇨🇳' },
  { name: 'South Ndebele', code: 'nr', flag: '🇿🇦' },
  { name: 'Occitan', code: 'oc', flag: '🇫🇷' },
  { name: 'Ojibwe, Ojibwa', code: 'oj', flag: '🇨🇦' },
  { name: 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic', code: 'cu', flag: '' },
  { name: 'Oromo', code: 'om', flag: '🇪🇹' },
  { name: 'Oriya', code: 'or', flag: '🇮🇳' },
  { name: 'Ossetian, Ossetic', code: 'os', flag: '🇷🇺' },
  { name: 'Panjabi, Punjabi', code: 'pa', flag: '🇮🇳' },
  { name: 'Pāli', code: 'pi', flag: '' },
  { name: 'Persian', code: 'fa', flag: '🇮🇷' },
  { name: 'Polish', code: 'pl', flag: '🇵🇱' },
  { name: 'Pashto, Pushto', code: 'ps', flag: '🇦🇫' },
  { name: 'Portuguese', code: 'pt', flag: '🇵🇹' },
  { name: 'Quechua', code: 'qu', flag: '🇵🇪' },
  { name: 'Romansh', code: 'rm', flag: '🇨🇭' },
  { name: 'Kirundi', code: 'rn', flag: '🇧🇮' },
  { name: 'Romanian, Moldavian, Moldovan', code: 'ro', flag: '🇷🇴' },
  { name: 'Russian', code: 'ru', flag: '🇷🇺' },
  { name: 'Sanskrit (Saṁskṛta)', code: 'sa', flag: '🇮🇳' },
  { name: 'Sardinian', code: 'sc', flag: '🇮🇹' },
  { name: 'Sindhi', code: 'sd', flag: '🇵🇰' },
  { name: 'Northern Sami', code: 'se', flag: '🇳🇴' },
  { name: 'Samoan', code: 'sm', flag: '🇼🇸' },
  { name: 'Sango', code: 'sg', flag: '🇨🇫' },
  { name: 'Serbian', code: 'sr', flag: '🇷🇸' },
  { name: 'Scottish Gaelic; Gaelic', code: 'gd', flag: '🇬🇧' },
  { name: 'Shona', code: 'sn', flag: '🇿🇼' },
  { name: 'Sinhala, Sinhalese', code: 'si', flag: '🇱🇰' },
  { name: 'Slovak', code: 'sk', flag: '🇸🇰' },
  { name: 'Slovene', code: 'sl', flag: '🇸🇮' },
  { name: 'Somali', code: 'so', flag: '🇸🇴' },
  { name: 'Southern Sotho', code: 'st', flag: '🇱🇸' },
  { name: 'Spanish; Castilian', code: 'es', flag: '🇪🇸' },
  { name: 'Sundanese', code: 'su', flag: '🇮🇩' },
  { name: 'Swahili', code: 'sw', flag: '🇰🇪' },
  { name: 'Swati', code: 'ss', flag: '🇸🇿' },
  { name: 'Swedish', code: 'sv', flag: '🇸🇪' },
  { name: 'Tamil', code: 'ta', flag: '🇮🇳' },
  { name: 'Telugu', code: 'te', flag: '🇮🇳' },
  { name: 'Tajik', code: 'tg', flag: '🇹🇯' },
  { name: 'Thai', code: 'th', flag: '🇹🇭' },
  { name: 'Tigrinya', code: 'ti', flag: '🇪🇷' },
  { name: 'Tibetan Standard, Tibetan, Central', code: 'bo', flag: '🇨🇳' },
  { name: 'Turkmen', code: 'tk', flag: '🇹🇲' },
  { name: 'Tagalog', code: 'tl', flag: '🇵🇭' },
  { name: 'Tswana', code: 'tn', flag: '🇧🇼' },
  { name: 'Tonga (Tonga Islands)', code: 'to', flag: '🇹🇴' },
  { name: 'Turkish', code: 'tr', flag: '🇹🇷' },
  { name: 'Tsonga', code: 'ts', flag: '🇿🇦' },
  { name: 'Tatar', code: 'tt', flag: '🇷🇺' },
  { name: 'Twi', code: 'tw', flag: '🇬🇭' },
  { name: 'Tahitian', code: 'ty', flag: '🇵🇫' },
  { name: 'Uighur, Uyghur', code: 'ug', flag: '🇨🇳' },
  { name: 'Ukrainian', code: 'uk', flag: '🇺🇦' },
  { name: 'Urdu', code: 'ur', flag: '🇵🇰' },
  { name: 'Uzbek', code: 'uz', flag: '🇺🇿' },
  { name: 'Venda', code: 've', flag: '🇿🇦' },
  { name: 'Vietnamese', code: 'vi', flag: '🇻🇳' },
  { name: 'Volapük', code: 'vo', flag: '' },
  { name: 'Walloon', code: 'wa', flag: '🇧🇪' },
  { name: 'Welsh', code: 'cy', flag: '🇬🇧' },
  { name: 'Wolof', code: 'wo', flag: '🇸🇳' },
  { name: 'Western Frisian', code: 'fy', flag: '🇳🇱' },
  { name: 'Xhosa', code: 'xh', flag: '🇿🇦' },
  { name: 'Yiddish', code: 'yi', flag: '🇮🇱' },
  { name: 'Yoruba', code: 'yo', flag: '🇳🇬' },
  { name: 'Zhuang, Chuang', code: 'za', flag: '🇨🇳' },
] as const;
